BoaUAT/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Air_Freight_Lead_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Air Freight Lead Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Need_Order_Number__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Order Number</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pop_up_Alert__c</fullName>
        <label>Pop up Alert</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sea_Freight_Lead_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sea Freight Lead Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Enterprise Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Supplier</fullName>
        <active>true</active>
        <label>Supplier</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/objects/Delivery_Address__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customers__c</fullName>
        <label>Customers</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Delivery Addresses</relationshipLabel>
        <relationshipName>Delivery_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if address is defiend as primary for that customer or not.</description>
        <label>Is Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Delivery Address</label>
    <nameField>
        <displayFormat>DA{0000}</displayFormat>
        <label>Delivery Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BoaUAT/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Time__c</fullName>
        <label>Lead Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sea Freight Lead Time</fullName>
                </value>
                <value>
                    <fullName>Air Freight Lead Time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Source__c</fullName>
        <label>Order Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WP-Order</fullName>
                </value>
                <value>
                    <fullName>M-Order</fullName>
                </value>
                <value>
                    <fullName>SF-Order</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Walk-In</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>city__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>default_Location__c</fullName>
        <label>Default Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>postal_code__c</fullName>
        <label>Postal Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

BoaUAT/src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Retail Customers</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/objects/Pricing_Policy_with_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Customers__c</fullName>
        <label>Customers</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Account doesn&apos;t exist or it should be of customer type.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Enterprise Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pricing Policies with Customers</relationshipLabel>
        <relationshipName>Pricing_Policies_with_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pricing Policy with Customer</label>
    <nameField>
        <label>Pricing Policy with Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Policies with Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BoaUAT/src/classes/NewOrder_SearchAccounts.cls
public with sharing class NewOrder_SearchAccounts {
    
    @AuraEnabled
    public static String searchAcc(String accountName,String objType,String type){
        if(type == 'customer'){
            try{
                if(accountName.length() == 0){
                    return null;
                }
                else{               
                    String sobject_type = objType;
                    Id customerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
                    Id retailCustomerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
                    Map<String, Schema.SObjectType> global_describe = Schema.getGlobalDescribe();
                    Map<String, Schema.SObjectField> object_fields_map = global_describe.get(sobject_type).getDescribe().fields.getMap();
                    for (String fieldName: object_fields_map.keySet()) {
                        if(fieldName == 'name'){
                            String objList = 'SELECT Id,Name,Pop_up_Alert__c FROM ' + objType + ' WHERE Name LIKE \'%' + String.escapeSingleQuotes(accountName) + '%\' AND RecordTypeId IN (:customerRecordTypeId,:retailCustomerRecordTypeId) LIMIT 10';                                      
                            List<Sobject> acc = Database.query(objList);
                            return JSON.serialize(acc);
                        }
                        
                    }    
                    return '{"error": "Field name does not exists on ' + objType + ' Object"}';
                } 
            }
            catch(Exception e){
                return '{"error":"'+e.getMessage()+'"}';
            }
        }
        else if(type =='supplier'){
			try{
                if(accountName.length() == 0){
                    return null;
                }
                else{               
                    String sobject_type = objType;
		            Id supplierRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Supplier').getRecordTypeId();
                    Id retailCustomerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
                    Map<String, Schema.SObjectType> global_describe = Schema.getGlobalDescribe();
                    Map<String, Schema.SObjectField> object_fields_map = global_describe.get(sobject_type).getDescribe().fields.getMap();
                    for (String fieldName: object_fields_map.keySet()) {
                        if(fieldName == 'name'){
                            String objList = 'SELECT Id,Name,Pop_up_Alert__c FROM ' + objType + ' WHERE Name LIKE \'%' + String.escapeSingleQuotes(accountName) + '%\' AND RecordTypeId =: supplierRecordTypeId  LIMIT 10';                                      
                            List<Sobject> acc = Database.query(objList);
                            return JSON.serialize(acc);
                        }
                        
                    }    
                    return '{"error": "Field name does not exists on ' + objType + ' Object"}';
                } 
            }
            catch(Exception e){
                return '{"error":"'+e.getMessage()+'"}';
            }
        }
        else{
            return '{"error": "An error occurred"}';
        }
    }
    
    // Supplier Account
    @AuraEnabled
    public static String searchSupplierAcc(String accountName,String objType){
        try{
            if(accountName.length() == 0){
                return null;
            }
            else{               
                String sobject_type = objType;
                Id customerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Supplier').getRecordTypeId();
                Map<String, Schema.SObjectType> global_describe = Schema.getGlobalDescribe();
                Map<String, Schema.SObjectField> object_fields_map = global_describe.get(sobject_type).getDescribe().fields.getMap();
                for (String fieldName: object_fields_map.keySet()) {
                    if(fieldName == 'name'){
                        String objList = 'SELECT Id,Name,Pop_up_Alert__c FROM ' + objType + ' WHERE Name LIKE \'%' + String.escapeSingleQuotes(accountName) + '%\' AND RecordTypeId =: supplierRecordTypeId';                                      
                        List<Sobject> acc = Database.query(objList);
                        return JSON.serialize(acc);
                    }
                    
                }    
                return '{"error": "Field name does not exists on ' + objType + ' Object"}';
            } 
        }
        catch(Exception e){
            return '{"error":"'+e.getMessage()+'"}';
        }
    }
    
    @AuraEnabled
    public static String selectedAccDetails(String accId){
        String accObj = 'SELECT Id,Name FROM Account WHERE Id =:accId';
        try{
            Account acc = Database.query(accObj);  
            return JSON.serialize(acc);
        }
        catch(Exception e){
            return '{"error":"'+e.getMessage()+'"}';
        }       
    }
    
    @AuraEnabled
    public static String selectedAccInfo(String accId, String type){
        if(type == 'customer'){
            System.debug('customer');
            String accObj = 'SELECT Id,Name,ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, ShippingCountry, Pop_up_Alert__c, Owner.Name, CurrencyIsoCode, Sea_Freight_Lead_Time__c, Air_Freight_Lead_Time__c, Need_Order_Number__c,(SELECT Customers__c, City__c,Country__c,Is_Primary__c,Postal_Code__c,Region__c,State__c,Street__c FROM Delivery_Addresses__r) FROM Account WHERE Id =:accId';
            String accPricingPolicy = 'SELECT Id FROM Pricing_Policy_with_Customer__c WHERE Customers__c =: accId';
            try{
                Account acc = Database.query(accObj);
                List<Delivery_Address__c> deladdr = acc.Delivery_Addresses__r;
                List<Pricing_Policy_with_Customer__c> accPricingP = Database.query(accPricingPolicy);
                String CurrencyIsoCode = acc.CurrencyIsoCode;
                String currencyInfo = 'SELECT ConversionRate FROM CurrencyType WHERE IsoCode =:CurrencyIsoCode AND IsActive = true';
                CurrencyType ct = Database.query(currencyInfo);
                String accountD = JSON.serialize(acc);
                String currencyT = JSON.serialize(ct);
                String oppLocList = picklistValues('Opportunity','default_Location__c');
                String oppStageList = picklistValues('Opportunity','StageName');
                String accPricingPExist = accPricingP.size() > 0 ? 'True' : 'False';
                String deliveryAddress = JSON.serialize(deladdr);
                String userList = JSON.serialize(salesUsersList());
                String oppTypeList = picklistValues('Opportunity','Type');
                String oppOrderSource = picklistValues('Opportunity','Order_Source__c');
                List<String> accDetailsWithCurrency = new List<String>();
                accDetailsWithCurrency.add(accountD);
                accDetailsWithCurrency.add(currencyT);
                accDetailsWithCurrency.add(oppLocList);
                accDetailsWithCurrency.add(oppStageList);
                accDetailsWithCurrency.add(accPricingPExist);
                accDetailsWithCurrency.add(deliveryAddress);
                accDetailsWithCurrency.add(userList);
                accDetailsWithCurrency.add(oppTypeList);
                accDetailsWithCurrency.add(oppOrderSource);
                return JSON.serialize(accDetailsWithCurrency);
            }
            catch(Exception e){
                return '{"error":"'+e.getMessage()+'"}';
            } 
        }
        else if(type == 'supplier'){
            String accObj = 'SELECT Id,Name,ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, ShippingCountry, Pop_up_Alert__c, Owner.Name, CurrencyIsoCode, Sea_Freight_Lead_Time__c, Air_Freight_Lead_Time__c, Need_Order_Number__c FROM Account WHERE Id =:accId';
            //String accPricingPolicy = 'SELECT Id FROM Pricing_Policy_with_Customer__c WHERE Customers__c =: accId';
            try{
                Account acc = Database.query(accObj);
                //List<Pricing_Policy_with_Customer__c> accPricingP = Database.query(accPricingPolicy);
                String CurrencyIsoCode = acc.CurrencyIsoCode;
                String currencyInfo = 'SELECT ConversionRate FROM CurrencyType WHERE IsoCode =:CurrencyIsoCode AND IsActive = true';
                CurrencyType ct = Database.query(currencyInfo);
                String accountD = JSON.serialize(acc);
                String currencyT = JSON.serialize(ct);
                String oppLocList = picklistValues('Opportunity','default_Location__c');
                String oppStageList = picklistValues('Opportunity','StageName');
                String oppLeadTimeList = picklistValues('Opportunity','Lead_Time__c');
                String userList = JSON.serialize(salesUsersList());
                //String accPricingPExist = accPricingP.size() > 0 ? 'True' : 'False';              
                    
                List<String> accDetailsWithCurrency = new List<String>();
                accDetailsWithCurrency.add(accountD);
                accDetailsWithCurrency.add(currencyT);
                accDetailsWithCurrency.add(oppLocList);
                accDetailsWithCurrency.add(oppStageList);
                //accDetailsWithCurrency.add(accPricingPExist);
                accDetailsWithCurrency.add(oppLeadTimeList);
                accDetailsWithCurrency.add(userList);
                
                return JSON.serialize(accDetailsWithCurrency);
            }
            catch(Exception e){
                return '{"error":"'+e.getMessage()+'"}';
            } 
        }
        else{
            return '{"error": "An error occurred"}';
        }
              
    }

    public static List<PickListEntries> salesUsersList(){
        
        List<PickListEntries> options = new List<PickListEntries>();
        String[] userL = Label.Sales_Users.split(',');
        List<User> salesUsersList = [SELECT Id,Name,Profile.Name FROM User WHERE Profile.Name IN : userL AND Name NOT IN ('Integration User') AND IsActive = true];
        
        for(User u : salesUsersList){
            options.add(new PickListEntries(u.Id,u.Name));
        }
        return options;
    }
    
    // Search contacts for Customer with Customer/Retail RecordType
    @AuraEnabled
    public static String searchContacts(String accId,String cntName){
        String cntObj = 'SELECT Id,Name,Email FROM Contact WHERE AccountId =:accId AND Name LIKE \'%' + String.escapeSingleQuotes(cntName) + '%\'';
        try{
            List<Contact> cnt = Database.query(cntObj);
            return JSON.serialize(cnt);
        }
        catch(Exception e){
            return '{"error":"'+e.getMessage()+'"}';
        }
    }
    
    public static String picklistValues(String objectName,String fieldName){
        Schema.SObjectType sobjType = Schema.getGlobalDescribe().get(objectName);
        Schema.DescribeSObjectResult objectResults = sobjType.getDescribe();
        Map<String,Schema.SObjectField> objectFields = objectResults.fields.getMap();
        Schema.DescribeFieldResult fieldResult = objectFields.get(fieldName).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        List<PickListEntries> options = new List<PickListEntries>();
        for( Schema.PicklistEntry f : ple){
            if(f.isActive() == true){
                options.add(new PickListEntries(f.getValue(),f.getLabel()));               
            }
        }     
        return JSON.serialize(options);
    }
    
    public class PickListEntries{
        public String value;
        public String label;
        
        public PickListEntries(String value,String label){
            this.value = value;
            this.label = label;
        }
    }
}