BoaUAT/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Full_Box_Coil_Percent__c</fullName>
        <label>Full Box/Coil Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pop_up_Alert__c</fullName>
        <label>Pop up Alert</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Supplier</fullName>
        <active>true</active>
        <label>Supplier</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <description>This field is used to specify the reason why the order was lost</description>
        <label>Closed Lost Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_Note__c</fullName>
        <label>Internal Note</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Time__c</fullName>
        <label>Lead Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sea Freight Lead Time</fullName>
                </value>
                <value>
                    <fullName>Air Freight Lead Time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>On_hold__c</fullName>
        <defaultValue>false</defaultValue>
        <label>On hold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Placed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Placed By</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>BOA Orders</relationshipLabel>
        <relationshipName>BOA_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Source__c</fullName>
        <label>Order Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WP-Order</fullName>
                </value>
                <value>
                    <fullName>M-Order</fullName>
                </value>
                <value>
                    <fullName>SF-Order</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Walk-In</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>city__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer_order_number__c</fullName>
        <label>Customer Order Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>default_Location__c</fullName>
        <label>Default Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>postal_code__c</fullName>
        <label>Postal Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>reference__c</fullName>
        <label>Customer Note</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

BoaUAT/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>EOQ__c</fullName>
        <defaultValue>0</defaultValue>
        <label>EOQ</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Full_Coil_Size_metre__c</fullName>
        <label>Full Coil Size - metre</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Group__c</fullName>
        <label>Price Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Price_Group</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>pop_up_alert__c</fullName>
        <label>Pop up Alert</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/objects/Stock_Item__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Stock Information</label>
</CustomObject>

BoaUAT/src/objects/Stock_Supplier__c.object
<CustomObject>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pack_Price__c</fullName>
        <label>Pack Price</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stock_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stock Item</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Stock Suppliers</relationshipLabel>
        <relationshipName>Stock_Suppliers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Code__c</fullName>
        <label>Supplier Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Customer doesn&apos;t exist or should be of supplier type.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Stock Suppliers</relationshipLabel>
        <relationshipName>Stock_Suppliers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stock Supplier</label>
    <nameField>
        <displayFormat>SP ={000000}</displayFormat>
        <label>Stock Supplier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/classes/EditOrder_ProdList.cls
public with sharing class EditOrder_ProdList {
    
    // for sales order
    @AuraEnabled
    public static String salesOrderEdit(String oppId){
        try{
            List<String> opportunityInfo = new List<String>();
            
            Opportunity oppt = [SELECT Id, Order_Source__c, Street__c, city__c, postal_code__c, state__c, Country__c, Order_Date__c, CloseDate, 
                                default_Location__c, OwnerId, On_hold__c, Internal_Note__c, reference__c, customer_order_number__c, 
                                StageName, Closed_Lost_Reason__c, Order_Placed_By__c, Order_Placed_By__r.Name, Type,
                                Account.CurrencyIsoCode,Account.Full_Box_Coil_Percent__c FROM Opportunity WHERE Id =: oppId];
            opportunityInfo.add(JSON.serialize(oppt));
            
            List<OpportunityLineItem> opl = [SELECT Id, PricebookEntryId,Product2Id, Product2.Name, Quantity, Product2.Price_Group__c, 
                                             ProductCode, UnitPrice, Discount,Description,Product2.Full_Coil_Size_metre__c,Product2.pop_up_alert__c,
                                             Opportunity.Account.Full_Box_Coil_Percent__c FROM OpportunityLineItem WHERE OpportunityId  =: oppId];
            
            List<ListOfSelectedProducts> lsp = new List<ListOfSelectedProducts>();
            if(!opl.isEmpty()){   
                for(OpportunityLineItem j : opl){
                    ListOfSelectedProducts sp = new ListOfSelectedProducts();
                    sp.Id = j.PricebookEntryId;
                    sp.productId = j.Product2Id;
                    sp.stockCode = j.Product2.Name;
                    sp.quantity = String.valueOf(j.Quantity);
                    sp.priceGroup = j.Product2.Price_Group__c;
                    sp.stockDescription = j.Description;
                    sp.UnitPrice = j.UnitPrice;
                    sp.discount = j.Discount;
                    sp.BasePrice = j.UnitPrice;
                    sp.pricingPolicyPrice = String.valueOf(j.UnitPrice);
                    sp.pricingPolicyRuleId = '';
                    sp.pricingPolicyquantity = String.valueOf(j.Quantity);
                    sp.fullCoilSize = j.Product2.Full_Coil_Size_metre__c;
                    sp.prevCoilDiscStat = false;
                    sp.fullCoilSizeDiscount = j.Opportunity.Account.Full_Box_Coil_Percent__c;
                    sp.productAlert = j.Product2.pop_up_alert__c;
                    lsp.add(sp);
                }   
            }
            
            opportunityInfo.add(JSON.serialize(lsp));
            opportunityInfo.add(currentUserProfileName());
            return JSON.serialize(opportunityInfo);
        }
        catch(Exception e){
            ErrorLogController.createErrorLog(e.getTypeName(),e.getMessage(),'NewOrder_ProductList.poPriceBookDataWithSearch',e.getLineNumber());
            return '{"error":"An error occurred"}';
        }
        
    }
    
    // purchase order
    @AuraEnabled
    public static String purchaseOrderEdit(String oppId){
        try{
            List<String> opportunityInfo = new List<String>();
            
            Opportunity oppt = [SELECT Id, Street__c, city__c, postal_code__c, state__c, Country__c, Order_Date__c, CloseDate, 
                                default_Location__c, OwnerId, Internal_Note__c, reference__c, Lead_Time__c, StageName, 
                                Closed_Lost_Reason__c, Order_Placed_By__c, Order_Placed_By__r.Name, Account.CurrencyIsoCode, AccountId 
                                FROM Opportunity WHERE Id =: oppId];
            opportunityInfo.add(JSON.serialize(oppt));
            
            List<OpportunityLineItem> opl = [SELECT Id, PricebookEntryId,Product2Id, Product2.Name, Quantity, Product2.Price_Group__c, ProductCode, UnitPrice, 
                                             Discount,Description FROM OpportunityLineItem WHERE OpportunityId =: oppId];
            
            List<PurchaseOrderSelectedProducts> lsp = new List<PurchaseOrderSelectedProducts>();
            
            
            List<Id> prodId = new List<Id>();
            
            Map<Id,Stock_Supplier__c> stockSuppl = new Map<Id,Stock_Supplier__c>();
            
            for(OpportunityLineItem j : opl){
                prodId.add(j.product2Id);
            }

            // Stock supplier records based on supplier and stock selected
            for(Stock_Supplier__c m : [SELECT Id, Discount_Percentage__c, Pack_Price__c, Supplier_Code__c, Stock_Item__c, Stock_Item__r.EOQ__c FROM Stock_Supplier__c WHERE Stock_Item__c IN : prodId AND Supplier_Name__c =: oppt.AccountId]){
                if(m != null){
                    stockSuppl.put(m.Stock_Item__c,m);                   
                }
            }
           
            System.debug('stockSuppl' + stockSuppl);
			
            /*
                for(OpportunityLineItem j : opl){
                    PurchaseOrderSelectedProducts sp = new PurchaseOrderSelectedProducts();
                    if(stockSuppl.get(j.product2Id) != null){                        
                        sp.Id = j.PricebookEntryId;
                        sp.productId = j.Product2Id;
                        sp.stockCode = j.Product2.Name;
                        sp.quantity = String.valueOf(j.Quantity);
                        sp.orderedQuantity = (stockSuppl.get(j.product2Id).Stock_Item__r.EOQ__c == null) ? String.valueOf(j.quantity) : String.valueOf(stockSuppl.get(j.product2Id).Stock_Item__r.EOQ__c);
                        sp.stockDescription = j.Description;
                        sp.UnitPrice = j.UnitPrice;
                        sp.discount = stockSuppl.get(j.product2Id).Discount_Percentage__c;
                        sp.packPrice = stockSuppl.get(j.product2Id).Pack_Price__c;
                        sp.supplierCode = stockSuppl.get(j.product2Id).Supplier_Code__c;
                    }
                    else{
                        sp.Id = j.PricebookEntryId;
                        sp.productId = j.Product2Id;
                        sp.stockCode = j.Product2.Name;
                        sp.quantity = String.valueOf(j.Quantity);
                        sp.orderedQuantity = String.valueOf(j.Quantity);
                        sp.stockDescription = j.Description;
                        sp.UnitPrice = j.UnitPrice;
                        sp.discount = j.Discount;
                        sp.packPrice = j.UnitPrice;
                        sp.supplierCode = '';
                    }
                   lsp.add(sp);
                }
              */
            for(OpportunityLineItem j : opl){
                PurchaseOrderSelectedProducts sp = new PurchaseOrderSelectedProducts();
                sp.Id = j.PricebookEntryId;
                sp.productId = j.Product2Id;
                sp.stockCode = j.Product2.Name;
                sp.quantity = String.valueOf(j.Quantity);
                sp.orderedQuantity = String.valueOf(j.Quantity);
                sp.stockDescription = j.Description;
                sp.UnitPrice = j.UnitPrice;
                sp.discount = j.Discount;
                sp.packPrice = j.UnitPrice;
                if(stockSuppl.get(j.product2Id) != null && stockSuppl.get(j.product2Id).Supplier_Code__c != null){
                    sp.supplierCode = stockSuppl.get(j.product2Id).Supplier_Code__c;
                }
                else{
                    sp.supplierCode = '';
                }
                
                lsp.add(sp);
            }
            
            opportunityInfo.add(JSON.serialize(lsp));
            opportunityInfo.add(currentUserProfileName());
            return JSON.serialize(opportunityInfo);
        }
        catch(Exception e){
            ErrorLogController.createErrorLog(e.getTypeName(),e.getMessage(),'NewOrder_ProductList.poPriceBookDataWithSearch',e.getLineNumber());
            return '{"error":"An error occurred"}';
        }
        
    }
    
    @testVisible
    private Static String currentUserProfileName(){
        try{
            return [SELECT Profile.Name FROM User WHERE Id =: UserInfo.getUserId() AND isActive = true].Profile.Name;
        }
        catch(Exception e){
            ErrorLogController.createErrorLog(e.getTypeName(),e.getMessage(),'NewOrder_ProductList.userProfile',e.getLineNumber());
            return 'error';
        }
    }
    
    // for sales order
    private class ListOfSelectedProducts{
        public String Id;
        public String productId;
        public String stockCode;
        public String quantity;
        public String priceGroup;
        public String stockDescription;
        public Double UnitPrice;
        public Double discount;
        public Double BasePrice;
        public String pricingPolicyPrice;
        public String pricingPolicyRuleId;
        public String pricingPolicyquantity; 
        public String fullCoilSize;
        public Double fullCoilSizeDiscount;
        public Boolean prevCoilDiscStat;
        public String productAlert;
    }
    
      // for purchase order
    private class PurchaseOrderSelectedProducts{
        public String Id;
        public String productId;
        public String stockCode;
        public String stockDescription;
        public String orderedQuantity;
        public String quantity;        
        public Double UnitPrice;
        public Double packPrice;
        public Double discount;
		public String supplierCode;
        public String productAlert;
    }
}