BoaUAT/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Pop_up_Alert__c</fullName>
        <label>Pop up Alert</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>override_GST_rate__c</fullName>
        <label>Override GST rate</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>-1</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>GST RateAuto Select Rate</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Supplier</fullName>
        <active>true</active>
        <label>Supplier</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/objects/ObjectAutoNumber__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to store the objects auto number values.</description>
    <fields>
        <fullName>Purchase_Order_No__c</fullName>
        <label>Purchase Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Object Auto Number</label>
</CustomObject>

BoaUAT/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <description>This field is used to specify the reason why the order was lost</description>
        <label>Closed Lost Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Email_id__c</fullName>
        <label>Contact Email id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_Note__c</fullName>
        <label>Internal Note</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Time__c</fullName>
        <label>Lead Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sea Freight Lead Time</fullName>
                </value>
                <value>
                    <fullName>Air Freight Lead Time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Placed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Placed By</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>BOA Orders</relationshipLabel>
        <relationshipName>BOA_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>city__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>default_Location__c</fullName>
        <label>Default Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>postal_code__c</fullName>
        <label>Postal Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>reference__c</fullName>
        <label>Customer Note</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subtotal__c</fullName>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>tax_total__c</fullName>
        <label>Tax Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Purchase_Order</fullName>
        <active>true</active>
        <businessProcess>Sales Process</businessProcess>
        <label>Purchase Order</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

BoaUAT/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>EOQ__c</fullName>
        <defaultValue>0</defaultValue>
        <label>EOQ</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Group__c</fullName>
        <label>Price Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Price_Group</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stock_Item_Url__c</fullName>
        <formula>&apos;https://silv--boasales.lightning.force.com/&apos; &amp; Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stock Item Url</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pop_up_alert__c</fullName>
        <label>Pop up Alert</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/objects/Stock_Item__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Stock Information</label>
</CustomObject>

BoaUAT/src/objects/Stock_Supplier__c.object
<CustomObject>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pack_Price__c</fullName>
        <label>Pack Price</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stock_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stock Item</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Stock Suppliers</relationshipLabel>
        <relationshipName>Stock_Suppliers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Code__c</fullName>
        <label>Supplier Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Customer doesn&apos;t exist or should be of supplier type.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Stock Suppliers</relationshipLabel>
        <relationshipName>Stock_Suppliers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stock Supplier</label>
    <nameField>
        <displayFormat>SP ={000000}</displayFormat>
        <label>Stock Supplier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/classes/NewOrder_CreatePurchaseOrder.cls
/*
@Purpose - Used to create new order and its line items for Purchase Order
@CreatedBy - Centelon Team 
*/
public with sharing class NewOrder_CreatePurchaseOrder {
    
    @AuraEnabled
    public static String createOrder(String orderData, String productData){
        Savepoint sp = Database.setSavepoint();
        try{
            
            Decimal TotalVal = 0.0;
            Decimal taxPercent = 0.0;
            Decimal taxAmt = 0.0;
            //Decimal totalAmountWithTax = 0.0;
            
            String oppPurchaseRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Purchase_Order').getRecordTypeId();
            
            PurchaseOrderAccountDetails ad = (PurchaseOrderAccountDetails)JSON.deserialize(orderData, PurchaseOrderAccountDetails.class);
            
            List<OrderProducts> op = (List<OrderProducts>)JSON.deserialize(productData, List<OrderProducts>.class);
            
            System.debug('PurchaseOrderAccountDetails ' + ad);
            System.debug('orderProd ' + op);
            if(op.size() == 0){
                return '{"emptyProdList":"Order cannot be created without stock item/s"}';
            }   
            else{
                
                Account acct = [SELECT override_GST_rate__c FROM Account WHERE Id=:ad.Id];
               
                if(String.isNotBlank(acct.override_GST_rate__c)){
                    String gstRate = SFToExoIntegrationUtility.getPicklistLabel('Account','override_GST_rate__c',acct.override_GST_rate__c);
                    if(gstRate == 'Auto Select Rate'){
                        taxPercent = Decimal.valueOf(Label.CustomerAutoSelectGStRate);
                    }
                    else{
                        String[] gr = gstRate.split('%');
                        taxPercent = Decimal.valueOf(gr[0]);
                    }
                }
                
                for(OrderProducts b : op){
                    Decimal prodTotal = (Double.valueOf(b.packprice) * Double.valueOf(b.orderedQuantity)) - ((Double.valueOf(b.packprice) * Double.valueOf(b.orderedQuantity)) * (Double.valueOf(b.discount)/100));
                    TotalVal += prodTotal;
                }
                
                taxAmt = TotalVal * (taxPercent/100);
                //totalAmountWithTax = TotalVal + taxAmt;
                
                // Auto number custom setting
                ObjectAutoNumber__c t = ObjectAutoNumber__c.getInstance('Opportunity');
                Opportunity opp = new Opportunity();
                
                if(String.isBlank(ad.opportunityId)){
                    t.Purchase_Order_No__c += 1;
                    update t;
                    opp.Name = String.valueOf(Integer.valueOf(t.Purchase_Order_No__c));
                }
                
                if(String.isNotBlank(ad.opportunityId)){
                    opp.Id = ad.opportunityId;
                } 
                opp.AccountId = ad.Id;
                opp.CloseDate = (ad.dueDate != null || ad.dueDate != '') ? Date.valueOf(ad.dueDate) : Date.today();
                opp.Order_Date__c = (ad.orderDate != null || ad.orderDate != '') ? Date.valueOf(ad.orderDate) : Date.today();
                opp.StageName = ad.selecteddOppStageVal;
                opp.reference__c = ad.reference;
                opp.Internal_Note__c = ad.internalNote;
                opp.default_Location__c = ad.selecteddLocVal;
                opp.Street__c = ad.ShippingStreet;
                opp.city__c = ad.ShippingCity;
                opp.postal_code__c = ad.ShippingPostalCode;
                opp.state__c = ad.ShippingState;
                opp.Country__c = ad.ShippingCountry;
                opp.RecordTypeId = oppPurchaseRecordTypeId;
                opp.CurrencyIsoCode = ad.CurrencyIsoCode;
                opp.Lead_Time__c = ad.selectedLeadTime;
                opp.OwnerId = ad.salesPersonSelectedVal;
                if(String.isNotBlank(ad.selectedContactId)){
                    //opp.Contact_Email_id__c = [SELECT Email FROM Contact WHERE Id =: ad.selectedContactId].Email;
                    opp.Order_Placed_By__c = ad.selectedContactId;
                }
                if(String.isNotBlank(ad.closedLostReason)){
                    opp.Closed_Lost_Reason__c = ad.closedLostReason;
                }

                opp.Pricebook2Id = [SELECT Id FROM Pricebook2 WHERE Name = 'Supplier Price book'].Id;
                opp.subtotal__c = TotalVal;
                opp.tax_total__c = taxAmt;
                
                upsert opp;
                
                List<OpportunityLineItem> oppL = new List<OpportunityLineItem>();                
                
                if(String.isBlank(ad.opportunityId)){
                    if(op.size() > 0){
                        for(Integer i = 0; i < op.size(); i++){
                            OpportunityLineItem oppLIt = new OpportunityLineItem();
                            oppLIt.PricebookEntryId = op[i].Id;
                            oppLIt.UnitPrice = Double.valueOf(op[i].packprice);
                            oppLIt.Quantity = Double.valueOf(op[i].orderedQuantity);
                            oppLIt.Discount = Double.valueOf(op[i].discount);
                            oppLit.Description = op[i].stockDescription;
                            oppLIt.OpportunityId = opp.Id;
                            oppL.add(oppLIt);
                        }
                    }
                }
                
                if(String.isNotBlank(ad.opportunityId)){
                    List<OpportunityLineItem> opl = [SELECT Id, Description, OpportunityId, PricebookEntryId,Product2Id, Product2.Name, Quantity, Product2.Price_Group__c, ProductCode, UnitPrice, 
                                             Discount FROM OpportunityLineItem WHERE OpportunityId =: ad.opportunityId];
                    
                    delete opl;
                    
                    for(Integer i = 0; i < op.size(); i++){
                        OpportunityLineItem oppLIt = new OpportunityLineItem();
                        oppLIt.PricebookEntryId = op[i].Id;
                        oppLIt.UnitPrice = Double.valueOf(op[i].packprice);
                        oppLIt.Quantity = Double.valueOf(op[i].orderedQuantity);
                        oppLIt.Discount = Double.valueOf(op[i].discount);
                        oppLit.Description = op[i].stockDescription;
                        oppLIt.OpportunityId = opp.Id;
                        oppL.add(oppLIt);
                    }
                    
                }
                
                
                /*if(op.size() > 0){
                    for(Integer i = 0; i < op.size(); i++){
                        OpportunityLineItem oppLIt = new OpportunityLineItem();
                        oppLIt.PricebookEntryId = op[i].Id;
                        oppLIt.UnitPrice = Double.valueOf(op[i].packprice);
                        oppLIt.Quantity = Double.valueOf(op[i].orderedQuantity);
                        oppLIt.Discount = Double.valueOf(op[i].discount);
                        oppLit.Description = op[i].stockDescription;
                        oppLIt.OpportunityId = opp.Id;
                        oppL.add(oppLIt);
                    }
                //}
                */
                System.debug('opp ' + opp.Id);
                
                upsert oppL;
                
                return '{"success":"' + opp.Id + '"}'; 
            }
        }
        catch(Exception e){
            Database.rollback(sp);
            ErrorLogController.createErrorLog(e.getTypeName(),e.getMessage(),'NewOrder_CreatePurchaseOrder.createOrder',e.getLineNumber()); 
            return '{"error":"An error occurred. Please contact your Administrator."}';
        }
        
    }
    
     // changed for new selected products design
     // for purchase order with search
    @AuraEnabled
    public static String poPriceBookDataWithSearch(String searchString,String accId){
        try{
            system.debug('accId ' + accId);       
            Id supplierPriceBookId   = [SELECT id FROM Pricebook2 WHERE Name = 'Supplier Price book' limit 1].Id;
            String CurrencyIsoCode = [SELECT CurrencyIsoCode FROM Account WHERE Id =: accId LIMIT 1].CurrencyIsoCode;
            List<PricebookEntry> pb = [SELECT Id,Name,UnitPrice,Product2.Id,Product2.Name,Product2.ProductCode,Product2.pop_up_alert__c,Product2.Stock_Item_Url__c,Product2.Price_Group__c FROM PricebookEntry WHERE Pricebook2Id =: supplierPriceBookId 
                                       AND ((Product2.Name LIKE :('%' + String.escapeSingleQuotes(searchString) + '%')) OR 
                                            Product2.ProductCode LIKE :('%' + String.escapeSingleQuotes(searchString) + '%')) AND Product2.IsActive = true AND CurrencyIsoCode =: CurrencyIsoCode LIMIT 10];        
            System.debug('pb ' + pb);
            return JSON.serialize(pb);  
        }
        catch(Exception e){
            ErrorLogController.createErrorLog(e.getTypeName(),e.getMessage(),'NewOrder_ProductList.poPriceBookDataWithSearch',e.getLineNumber());
            return '{"error":"'+e.getMessage()+'"}';
        }
        
    }
    
    @AuraEnabled
    public static String productPriceForPurchaseOrder(String accId, String selectedProd){        
        try{            
            PurchaseOrderSelectedProducts lsp = (PurchaseOrderSelectedProducts)JSON.deserialize(selectedProd, PurchaseOrderSelectedProducts.class);
 			
            System.debug('accId ' + accId);
            System.debug('prodId ' + lsp.productId);
            
            Map<Id,Stock_Supplier__c> stockSuppl = new Map<Id,Stock_Supplier__c>();

            // Stock supplier records based on supplier and stock selected
            for(Stock_Supplier__c m : [SELECT Id, Discount_Percentage__c, Pack_Price__c, Supplier_Code__c, Stock_Item__c, Stock_Item__r.EOQ__c, Stock_Item__r.ProductCode FROM Stock_Supplier__c WHERE Stock_Item__c =: lsp.productId AND Supplier_Name__c =: accId]){
                if(m != null){
                    stockSuppl.put(m.Stock_Item__c,m);                   
                }
            }
            
            System.debug('stockSuppl' + stockSuppl);
            
            if(stockSuppl.size() > 0){
                if(stockSuppl.get(lsp.productId) != null){                    
                    lsp.discount = stockSuppl.get(lsp.productId).Discount_Percentage__c;
                    lsp.packPrice = stockSuppl.get(lsp.productId).Pack_Price__c;				
                    lsp.supplierCode = stockSuppl.get(lsp.productId).Supplier_Code__c;
                    lsp.orderedQuantity = (stockSuppl.get(lsp.productId).Stock_Item__r.EOQ__c == null) ? String.valueOf(lsp.orderedQuantity) : String.valueOf(stockSuppl.get(lsp.productId).Stock_Item__r.EOQ__c);
                    lsp.quantity = lsp.orderedQuantity;
                    lsp.stockDescription = stockSuppl.get(lsp.productId).Stock_Item__r.ProductCode;
                }
            }
            System.debug('lsp' + lsp);
            return JSON.serialize(lsp);
        }
        catch(Exception e){
            ErrorLogController.createErrorLog(e.getTypeName(),e.getMessage(),'NewOrder_ProductList.productPriceForPurchaseOrder',e.getLineNumber());
            return '';
        }
    }
    
    public class PurchaseOrderAccountDetails{
        public String Id;
        public String AccountName;
        public String ShippingStreet;	
        public String ShippingCity;	
        public String ShippingPostalCode;	
        public String ShippingState;	
        public String ShippingCountry;
        //public String OwnerId;
        public String CurrencyIsoCode;
        public String orderDate;
        public String dueDate;	
        public String reference;  
        public String internalNote;  
        public String selecteddLocVal;
        public String selecteddOppStageVal;  
        public String selectedLeadTime;
        public String salesPersonSelectedVal;
        public String selectedContactId;
        public String closedLostReason;
        public String opportunityId;
    }
    
    public class OrderProducts{
        public String id;
        public String stockCode;
        public String orderedQuantity;
        public String stockDescription;
        public Double packprice;
        public Double discount;
    }
    
     public class PurchaseOrderSelectedProducts{
        public String Id;
        public String productId;
        public String stockCode;
        public String stockDescription;
        public String orderedQuantity;
        public String quantity;        
        public Double UnitPrice;
        public Double packPrice;
        public Double discount;
		public String supplierCode;
        public String productAlert; 
    }
    
    
}