BoaUAT/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Base_Price__c</fullName>
        <label>Base Price</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Class__c</fullName>
        <label>Customer Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Person_Code_in_Exo__c</fullName>
        <description>This stores exo code of sales person for SF to EXo integration purpose. Not to be shown on page layout.</description>
        <label>Sales Person Code in Exo</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Sales_Person_Code_in_Exo__c</fullName>
        <label>Sales Person Code in Exo</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BoaUAT/src/objects/Sales_Person__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores sales person to its code map in salesforce</description>
    <fields>
        <fullName>Staff_Number__c</fullName>
        <description>Staff no in Exo from Staff table</description>
        <label>Staff Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales person</label>
</CustomObject>

BoaUAT/src/classes/SFToExoIntegrationUtilityTest.cls
@isTest
public class SFToExoIntegrationUtilityTest{
    static testMethod void testSFTOEXOIntegrationUtility(){
        
        list<id> recordIds= new list<id>();           
        Account testAccount = new Account();
        testAccount.Name='Account' ;
        testAccount.Region__c='CHINA';
        testAccount.Base_Price__c='Retail';
        testAccount.Customer_Class__c='AA(A Active)';
        testAccount.Email__c='krutika@centelon.com';
        upsert testAccount;
       // update testAccount; 
        Contact cont = new Contact();
        cont.LastName='Test';
         //cont.Accountid= testAccount.id;
        upsert cont;
       //update cont;
        recordIds.add(testAccount.id);
        recordIds.add(cont.AccountId);

        // recordIds.add('asdc','test','opl'); 
       // Account Acc = [select id,name from Account where Id='0010l00000QJwpd'];
       // Acc.Name='CA';
 // A
       // update Acc;
         //update = recordIds;
        // if(!updateAccounts.isEmpty()) update updateAccounts;
             //   if(!updateContacts.isEmpty()) update updateContacts;
                
        SFToExoIntegrationUtility.assignExoStaffCode(recordIds);
      
    }
    static testMethod void testSFTOEXOIntegrationUtility2(){
     
   list<id> recIds= new list<id>();
        Account acc = new Account();
            acc.Name = 'testaccount';
            acc.Region__c='CHINA';
        acc.Base_Price__c='Retail';
        acc.Customer_Class__c='AA(A Active)';
        acc.Email__c='krutika@centelon.com';
                 insert acc;      
           map<id,string> ownerNamesToRecordId = new map<id,string>();
        
        map<string,sales_person__c> salesPersonMap = sales_person__c.getAll();
        
                for(id recordId: ownerNamesToRecordId.keyset()){
                    
                    sales_person__c salesPerson = salesPersonMap.get(ownerNamesToRecordId.get(recordId)); 
                    if(salesPerson ==  null){
                        salesPerson = salesPersonMap.get('Integration User');     
                    }     
                        
        Contact con = new Contact();
            //AccountId = acc.id;
             acc.Id=con.AccountId;
            con.LastName = 'testcontact';
            con.Sales_Person_Code_in_Exo__c= salesPerson.staff_number__c;
       
            
            //,RecordTypeId = contExhibitorRT.Id //Set this contact to the exhibitor record type
        
        insert con;

        acc.Region__c = 'Aukland';      
        Test.startTest();
        update acc;
        Test.stopTest();
        

        //Requery the contact record and check to make sure it was updated.
        Contact result = [Select Lastname,Department,MailingAddress From Contact ];
        //System.assertEquals(con.FirstName,result.Lastname);
         SFToExoIntegrationUtility.assignExoStaffCode(recIds);
    
}
    }
}