BoaUAT/src/objects/Credit_Application_Form__c.object
<CustomObject>
    <description>Used to store CAF information for particular customer. This object wont be there in EXO system.</description>
    <fields>
        <fullName>ProcessRefrence__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProcessRefrence</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Application Form</label>
    <nameField>
        <displayFormat>CAF-{0000}</displayFormat>
        <label>Credit Application Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Application Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/classes/SendtoDocusignProcessbuider.cls
public class SendtoDocusignProcessbuider {
    @InvocableMethod
    public Static void SendtoDocuFuture(List<Id> CreditappId){
        System.debug('CreditappId ' + CreditappId);
        SendToDocuSignweb.SendNow(CreditappId[0]);
        //Credit_Application_Form__c c = new Credit_Application_Form__c(Id=CreditappId[0]);
        //c.ProcessRefrence__c = false;
        //update c;
        
        //System.debug('after future finish');
        
    }
    
    @future(callout=true)
        public Static void conPdfFuture(String CreditappId){
            SendToDocuSignweb.SendNow(CreditappId);
            Credit_Application_Form__c c = new Credit_Application_Form__c(Id=CreditappId);
            c.ProcessRefrence__c = false;
            update c;
        }
    }