BoaUAT/src/objects/Delivery_Address__c.object
<CustomObject>
    <fields>
        <fullName>Customers__c</fullName>
        <label>Customers</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Delivery Addresses</relationshipLabel>
        <relationshipName>Delivery_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Delivery Address</label>
    <nameField>
        <displayFormat>DA{0000}</displayFormat>
        <label>Delivery Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BoaUAT/src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Standard_Cost__c</fullName>
        <description>STDCOST in EXO Stock_Items Object.</description>
        <label>Standard Cost</label>
        <precision>17</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

BoaUAT/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Bill_of_Material__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill of Material</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuantityUnitOfMeasure__c</fullName>
        <label>Pack</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASSEMBLY</fullName>
                </value>
                <value>
                    <fullName>DRUM</fullName>
                </value>
                <value>
                    <fullName>EACH</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>PACK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>is_Hydraulic_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field identifies stock Item as a hydraulic product. This products are to be synced with web site and web portal.</description>
        <inlineHelpText>If true,this product is to be synced with web site and web portal.</inlineHelpText>
        <label>is Hydraulic Product</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/objects/session_Tokens__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will store latest valid tokens from external systems like web site, web portal, mobile app.</description>
    <fields>
        <fullName>token__c</fullName>
        <label>token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>session tokens</label>
</CustomObject>

BoaUAT/src/objects/web_portal_creds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores end points and all the creds for web portal call</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>web portal creds</label>
</CustomObject>

BoaUAT/src/classes/Test_Rest_WebPortalOutboundHandler.cls
@isTest
public class Test_Rest_WebPortalOutboundHandler {
	
    public static testMethod void unitTest(){
        
        Account a = new Account();
        a.Name = 'Test Account';
        insert a;
        
        delivery_Address__c da = new Delivery_Address__c();
        da.Customers__c = a.Id;
        da.Postal_Code__c = '1022';
        insert da;
        
        Contact c = new Contact();
        c.AccountId = a.Id;
        c.LastName = 'Last Name';
        insert c;
        
        Product2 p = new Product2();
        p.Name = 'Test Product';
        p.QuantityUnitOfMeasure__c = 'PACK';
        p.is_Hydraulic_Product__c = true;
        p.Bill_of_Material__c = false;
        insert p;
        
        Pricebook2 pb = new PriceBook2();
        pb.Name = 'Standard PriceBook';
        pb.IsActive = true;
        pb.CurrencyIsoCode = 'NZD';
        //pb.IsStandard = true;
        insert pb;

		String standardPricebookId = Test.getStandardPricebookId();

        PriceBookEntry pbe = new PriceBookEntry();
        pbe.Pricebook2Id = standardPricebookId;
        //pbe.Pricebook2Id = pb.Id;
        pbe.Product2Id = p.Id;
        pbe.UnitPrice = 20.50;
        pbe.Standard_Cost__c = 10.10;
        //pbe.UseStandardPrice = false;        
        pbe.IsActive = true;
        pbe.CurrencyIsoCode = 'NZD';
        insert pbe; 
        
        PriceBookEntry customPriceBookEntry = new PriceBookEntry();
        customPriceBookEntry.Product2Id=p.Id;
        customPriceBookEntry.Pricebook2Id=pb.Id;
        customPriceBookEntry.UnitPrice=5000;
        customPriceBookEntry.IsActive=true;
        insert customPriceBookEntry;
        
        List<Id> conIds = new List<Id>();
        conIds.add(c.Id);
        List<Id> prodIds = new List<Id>();
        prodIds.add(p.Id);
        
        web_portal_creds__c cred = new web_portal_creds__c();
        cred.Name = 'email';
        cred.Value__c = 'salesforce.integration@centelon.com';
        insert cred;
        
        web_portal_creds__c cred1 = new web_portal_creds__c();
        cred1.Name = 'endpoint';
        cred1.Value__c = 'https://dev-portal-api.boa.co.nz';
        insert cred1;
        
        web_portal_creds__c cred2 = new web_portal_creds__c();
        cred2.Name = 'password';
        cred2.Value__c = 'Password@123';
        insert cred2;
        
        web_portal_creds__c cred3 = new web_portal_creds__c();
        cred3.Name = 'x-api-key';
        cred3.Value__c = 'boatestappkey';
        insert cred3;
        
        session_Tokens__c st = new session_Tokens__c();
        st.Name = 'web_portal';
        st.token__c = 'yrYAhSJ29rSEIMU08Qv36ZsBV3GU4bBW';
        insert st;
        
        Rest_WebPortalOutboundHandler.SendContactupdatesToPortal(conIds);
        Rest_WebPortalOutboundHandler.sendProductDetailsToPortal(prodIds);
    }
}