BoaUAT/src/objects/Error_Log__c.object
<CustomObject>
    <description>This object will store all the background errors.</description>
    <fields>
        <fullName>Error_Id__c</fullName>
        <label>Error Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Line_Number__c</fullName>
        <label>Error Line Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/classes/ErrorLogController.cls
public class ErrorLogController {
    
    public static void createErrorLog(string errorId,string errorMessage,string methodName,integer errorLineNumber){
         error_log__c el = new error_log__c();
         el.Error_Id__c = errorId;
         el.Error_Message__c = errorMessage;
         el.method_Name__c = methodName;
         el.error_Line_Number__c = errorLineNumber;  
         insert el; 
        
    }
    
}