BoaUAT/src/objects/Pricing_Policy__c.object
<CustomObject>
    <label>Pricing Policy</label>
    <nameField>
        <label>Pricing Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/objects/Pricing_Policy_with_Customer__c.object
<CustomObject>
    <fields>
        <fullName>Customers__c</fullName>
        <label>Customers</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Account doesn&apos;t exist or it should be of customer type.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Enterprise Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pricing Policies with Customers</relationshipLabel>
        <relationshipName>Pricing_Policies_with_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pricing_Policy__c</fullName>
        <label>Pricing Policy</label>
        <referenceTo>Pricing_Policy__c</referenceTo>
        <relationshipLabel>Pricing Policies with Cusotmers</relationshipLabel>
        <relationshipName>Pricing_Policies_with_Cusotmers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pricing Policy with Customer</label>
    <nameField>
        <label>Pricing Policy with Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Policies with Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BoaUAT/src/classes/Pricing_Policy.cls
global class Pricing_Policy {

     @InvocableMethod
    public static void PricingPolicy(List<Id> PolicyId){
        
        List<Account> accList = [select Id from Account WHERE RecordTypeId = '0120l000000BSDUAA4'];
        List<Pricing_Policy_with_Customer__c> ppcList = new List<Pricing_Policy_with_Customer__c>();
        for(Account acc : accList){ // for each account in accLis
        	
            Pricing_Policy_with_Customer__c ppc = new Pricing_Policy_with_Customer__c();
            ppc.Name = 'Special Off';
            ppc.Customers__c = acc.Id;
            ppc.Pricing_Policy__c = PolicyId[0];
            ppcList.add(ppc);
            //insert ppc;
    	}
        
        insert ppcList;
        
}
}