BoaUAT/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Bill_of_Material__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill of Material</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuantityUnitOfMeasure__c</fullName>
        <label>Pack</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASSEMBLY</fullName>
                </value>
                <value>
                    <fullName>DRUM</fullName>
                </value>
                <value>
                    <fullName>EACH</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>PACK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>is_Hydraulic_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field identifies stock Item as a hydraulic product. This products are to be synced with web site and web portal.</description>
        <inlineHelpText>If true,this product is to be synced with web site and web portal.</inlineHelpText>
        <label>is Hydraulic Product</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/classes/Test_Rest_websiteOutboundController.cls
@isTest
public class Test_Rest_websiteOutboundController {
	
    public static testMethod void unitTest(){
        Product2 p = new Product2();
        p.Name = 'Test Product';
        p.QuantityUnitOfMeasure__c = 'Each';
        p.is_Hydraulic_Product__c = true;
        p.Bill_of_Material__c = false;
        p.IsActive = true;
        
        insert p;
        
		List<id> stockIds = new List<id>();
		stockIds.add(p.Id);
        
        Rest_websiteOutboundController.SFtoWebSite innerObj = new Rest_websiteOutboundController.SFtoWebSite();
        innerObj.sObjectName = 'Product';
        innerObj.sObjectId = p.Id;
        
        List<Rest_websiteOutboundController.SFtoWebSite> classList = new List<Rest_websiteOutboundController.SFtoWebSite>();
        classList.add(innerObj);    
        
        Rest_websiteOutboundController.callerMethod(classList);
		Rest_websiteOutboundController.sendProductDetailstoWebSiteTrigger(stockIds);
		test.startTest();
        batchProductUploadToWebSite b = new batchProductUploadToWebSite();
		Database.executeBatch(b);
		test.stopTest();        
    }
}