BoaUAT/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>B_in__c</fullName>
        <label>B(in.)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_of_Material__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill of Material</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Collated_Identifier__c</fullName>
        <label>Collated Identifier</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DKOL_DKOS__c</fullName>
        <label>DKOL/DKOS</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D_in__c</fullName>
        <label>D (in.)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dash_Size_1__c</fullName>
        <label>Dash Size 1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dash_Size_2__c</fullName>
        <label>Dash Size 2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dash_Size_3__c</fullName>
        <label>Dash Size 3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dash_Size_4__c</fullName>
        <label>Dash Size 4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>E_in__c</fullName>
        <label>E (in.)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Coil_Size_metre__c</fullName>
        <label>Full Coil Size - metre</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>H1__c</fullName>
        <label>H1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>H2_Nut_Size__c</fullName>
        <label>H2 (Nut Size)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>H_in__c</fullName>
        <label>H (in.)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hose_Inner_Diameter_Inches__c</fullName>
        <label>Hose Inner Diameter Inches</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hose_Inner_Diameter_mm__c</fullName>
        <label>Hose Inner Diameter mm</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hose_Outer_Diameter_mm__c</fullName>
        <label>Hose Outer Diameter mm</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Identifier_related_info_Thread_2_ID__c</fullName>
        <label>Identifier/related info/Thread 2 ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LC_Length__c</fullName>
        <label>LC (Length)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LD_Drop__c</fullName>
        <label>LD (Drop)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L_in__c</fullName>
        <label>L (in.)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>M_in__c</fullName>
        <label>M (in.)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Male_Female_Flange_Fitting_Only__c</fullName>
        <label>Male/Female/Flange (Fitting Only)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Flow_L_Min__c</fullName>
        <label>Max Flow L/Min</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Work_Pressure_PSI__c</fullName>
        <label>Max Work Pressure (PSI</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Burst_Pressure_Female_PSI__c</fullName>
        <label>Min Burst Pressure Female (PSI)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Burst_Pressure_Male_PSI__c</fullName>
        <label>Min Burst Pressure Male (PSI)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Bend_Radius_mm__c</fullName>
        <label>Minimum Bend Radius mm</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nominal_Pipe_Size__c</fullName>
        <label>Nominal Pipe Size</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nominal_Size_mm__c</fullName>
        <label>Nominal Size (mm)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nominal_Thread_Size_1__c</fullName>
        <label>Nominal Thread Size 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nominal_Thread_Size_2__c</fullName>
        <label>Nominal Thread Size 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nominal_Thread_Size_3__c</fullName>
        <label>Nominal Thread Size 3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nominal_Thread_Size_4__c</fullName>
        <label>Nominal Thread Size 4</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Orientation__c</fullName>
        <label>Orientation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>45 Swept</fullName>
                </value>
                <value>
                    <fullName>90 Compact</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>90 Swept</fullName>
                </value>
                <value>
                    <fullName>45 Compact</fullName>
                </value>
                <value>
                    <fullName>STRAIGHT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Physical_Thread_Size_1__c</fullName>
        <label>Physical Thread Size 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Thread_Size_3__c</fullName>
        <label>Physical Thread Size 3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Thread_Size_4__c</fullName>
        <label>Physical Thread Size 4</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prefix_Thread_1_ID__c</fullName>
        <label>Prefix/Thread 1 ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Group__c</fullName>
        <description>This field is equivalent to Sales GL code in EXO.</description>
        <label>Primary Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Primary_Group</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Family_Display_Name__c</fullName>
        <label>Product Family Display Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuantityUnitOfMeasure__c</fullName>
        <label>Pack</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASSEMBLY</fullName>
                </value>
                <value>
                    <fullName>DRUM</fullName>
                </value>
                <value>
                    <fullName>EACH</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>PACK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rated_Flow_L_min__c</fullName>
        <label>Rated Flow L/min</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Secondary_Group_Display_Name__c</fullName>
        <label>Secondary Group Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Group__c</fullName>
        <label>Secondary Group</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Primary_Group__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Secondary_Group</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Show_on_Website__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show on Website</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stock_Image_1__c</fullName>
        <inlineHelpText>Stores link of product image from S3 bucket.</inlineHelpText>
        <label>Stock Image 1</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Stock_Image_2__c</fullName>
        <description>stores image url from s3 bucket.</description>
        <label>Stock Image 2</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Stock_Image_3__c</fullName>
        <description>stores image url from s3 bucket.</description>
        <label>Stock Image 3</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Suits_Hose__c</fullName>
        <label>Suits Hose</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tail_Size_To_Suit_Hose_ID__c</fullName>
        <label>Tail Size (To Suit Hose ID)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tertiary_Group_Display_Name__c</fullName>
        <label>Tertiary Group Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tertiary_Group__c</fullName>
        <label>Tertiary Group</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Secondary_Group__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Product_Tertiary_Group</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Thread_3_ID_SS_adaptor__c</fullName>
        <label>Thread 3 ID/SS adaptor</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thread_Color_Code__c</fullName>
        <label>Thread Color Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thread_Type_1__c</fullName>
        <label>Thread Type 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thread_Type_2__c</fullName>
        <label>Thread Type 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thread_Type_3__c</fullName>
        <label>Thread Type 3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thread_Type_4__c</fullName>
        <label>Thread Type 4</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thread_Type_Filter_1__c</fullName>
        <label>Thread Type Filter 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thread_Type_Filter_2__c</fullName>
        <label>Thread Type Filter 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WordPress_Id__c</fullName>
        <label>WordPress Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Working_Pressure_BAR__c</fullName>
        <label>Working Pressure BAR</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Working_Pressure_PSI__c</fullName>
        <label>Working Pressure PSI</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>is_Hydraulic_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field identifies stock Item as a hydraulic product. This products are to be synced with web site and web portal.</description>
        <inlineHelpText>If true,this product is to be synced with web site and web portal.</inlineHelpText>
        <label>is Hydraulic Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>physical_thread_size_2__c</fullName>
        <label>physical thread size 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/objects/Product_Category_Information__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Category_Id__c</fullName>
        <label>Category Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock_Description__c</fullName>
        <label>Stock Description</label>
        <type>TextArea</type>
    </fields>
    <label>Product Category Information</label>
</CustomObject>

BoaUAT/src/objects/web_site_creds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>consumer_key__c</fullName>
        <label>consumer key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>consumer_secret__c</fullName>
        <label>consumer secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endpoint__c</fullName>
        <label>endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>web site creds</label>
</CustomObject>

BoaUAT/src/classes/Test_RestwebSiteOutboundHandler.cls
@isTest
public class Test_RestwebSiteOutboundHandler {
	
    public static testMethod void unitTest(){
        
        web_site_creds__c cred = new web_site_creds__c();
        cred.Name = 'products';
        cred.consumer_key__c = 'ck_9eed31a9207af474c8b64c9dddfd5c0de1ec06f1';
        cred.consumer_secret__c = 'cs_6af3ecb6246a155804f3e8d6c7eb45755eeef7a2';
        cred.endpoint__c = 'https://test.boa.co.nz/wp-json/wc/v2/products';
        insert cred;    
        
        Product_Category_Information__c pci = new Product_Category_Information__c();
        pci.Name = 'Adaptors';
        pci.Category_Id__c = '11';
        pci.Stock_Description__c = 'Adaptors';
        
        insert pci;
        
        Product_Category_Information__c pci1 = new Product_Category_Information__c();
        pci1.Name = 'Straight Adaptors';
        pci1.Category_Id__c = '12';
        pci1.Stock_Description__c = 'Straight Adaptors';
        
        insert pci1;
        
        Product_Category_Information__c pci2 = new Product_Category_Information__c();
        pci2.Name = 'AA - BSPT MALE X BSPT MALE';
        pci2.Category_Id__c = '13';
        pci2.Stock_Description__c = 'AA - BSPT MALE X BSPT MALE';
        
        insert pci2;
        
        Product_Category_Information__c pci3 = new Product_Category_Information__c();
        pci3.Name = 'Sales - Hydraulic Fittings';
        pci3.Category_Id__c = '14';
        pci3.Stock_Description__c = 'Sales - Hydraulic Fittings';
        
        insert pci3;
        
        product2 p = new Product2();
        p.Name = 'Test Product';
        p.QuantityUnitOfMeasure__c = 'Each';
        p.is_Hydraulic_Product__c = true;
        p.Bill_of_Material__c = false;
        p.IsActive = true;
        p.Show_on_Website__c = true;
        p.WordPress_Id__c = '12345';
        p.Primary_Group__c = '1110-10';
        p.Secondary_Group__c = '15';
        p.Secondary_Group_Display_Name__c = 'Adaptors';
        p.Tertiary_Group__c = '320';
        p.Tertiary_Group_Display_Name__c = 'Straight Adaptors';
        p.Product_Family__c = 'AA';
        p.Product_Family_Display_Name__c = 'AA - BSPT MALE X BSPT MALE';
        p.nominal_thread_size_1__c = '1';
        p.nominal_thread_size_2__c = '2';
        p.nominal_thread_size_3__c = '3';
        p.nominal_thread_size_4__c = '4';
        p.Physical_Thread_Size_1__c = '1';
        p.Physical_Thread_Size_2__c = '2';
        p.Physical_Thread_Size_3__c = '3';
        p.Physical_Thread_Size_4__c = '4'; 
        p.Thread_Type_1__c = '1';
        p.Thread_Type_2__c = '2';
        p.Thread_Type_3__c = '3';
        p.Thread_Type_4__c = '4';
        p.Orientation__c = '45';
        p.Tail_Size_To_Suit_Hose_ID__c = '11';
        p.Nominal_Pipe_Size__c = '1/4';
        p.Thread_Type_Filter_1__c = '1';
        p.Thread_Type_Filter_2__c = '2'; 
        p.Stock_Image_1__c = 'Image 1';
        p.Stock_Image_2__c = 'Image 2';
        p.Stock_Image_3__c = 'Image 3'; 
        
        p.Prefix_Thread_1_ID__c = '1';
        p.Collated_Identifier__c = '2';
        p.Identifier_related_info_Thread_2_ID__c = '3';
        p.Thread_3_ID_SS_adaptor__c = '4';
        p.DKOL_DKOS__c = '5';
        p.Thread_Color_Code__c = '6';
        p.Male_Female_Flange_Fitting_Only__c = '7';
        p.Suits_Hose__c = '8';
        p.LC_Length__c = '9';
        p.LD_Drop__c = '10';
        p.H1__c = '11';
        p.H2_Nut_Size__c = '12';
            
        insert p;
    
    List<Id> stockList = new List<Id>();
    stockList.add(p.Id); 
        //Test.setMock(HttpCalloutMock.class, new MockCallOutATTCallouts());
        
    Rest_websiteOutboundHandler.sendProductDetailsToPublicSite(stockList);
        
    }
    
    public static testMethod void unitTest1(){
    	
        web_site_creds__c cred = new web_site_creds__c();
        cred.Name = 'products';
        cred.consumer_key__c = 'ck_9eed31a9207af474c8b64c9dddfd5c0de1ec06f1';
        cred.consumer_secret__c = 'cs_6af3ecb6246a155804f3e8d6c7eb45755eeef7a2';
        cred.endpoint__c = 'https://test.boa.co.nz/wp-json/wc/v2/products';
        insert cred;  
        
        Product_Category_Information__c pci = new Product_Category_Information__c();
        pci.Name = 'Hose';
        pci.Category_Id__c = '11';
        pci.Stock_Description__c = 'Hose';
        
        insert pci;
        
        Product_Category_Information__c pci1 = new Product_Category_Information__c();
        pci1.Name = 'Hydraulic Hose';
        pci1.Category_Id__c = '12';
        pci1.Stock_Description__c = 'Hydraulic Hose';
        
        insert pci1;
        
        Product_Category_Information__c pci2 = new Product_Category_Information__c();
        pci2.Name = 'SF1SN';
        pci2.Category_Id__c = '13';
        pci2.Stock_Description__c = 'SF1SN - SILFLO 1SN/1AT 1-WIRE HYDRAULIC HOSE';
        
        insert pci2;
        
        Product_Category_Information__c pci3 = new Product_Category_Information__c();
        pci3.Name = 'Sales - Hydraulic Hose';
        pci3.Category_Id__c = '14';
        pci3.Stock_Description__c = 'Sales - Hydraulic Hose';
        
        insert pci3;
        
        product2 p = new Product2();
        p.Name = 'Test Product';
        p.QuantityUnitOfMeasure__c = 'Each';
        p.is_Hydraulic_Product__c = true;
        p.Bill_of_Material__c = false;
        p.IsActive = true;
        p.Show_on_Website__c = true;
        p.WordPress_Id__c = '';
        p.Primary_Group__c = '1110-11';
        p.Secondary_Group__c = '2';
        p.Secondary_Group_Display_Name__c = 'Hose';
        p.Tertiary_Group__c = '48';
        p.Tertiary_Group_Display_Name__c = 'Hydraulic Hose';
        p.Product_Family__c = 'SF1SN';
        p.Product_Family_Display_Name__c = 'SF1SN - SILFLO 1SN/1AT 1-WIRE HYDRAULIC HOSE';
        p.Hose_Inner_Diameter_Inches__c = '1';
        p.Hose_Inner_Diameter_mm__c = 2;
        p.Working_Pressure_PSI__c = 3;
        p.Hose_Outer_Diameter_mm__c = 4;
        p.Working_Pressure_BAR__c = 1;
        p.Minimum_Bend_Radius_mm__c = 2;
        p.Full_Coil_Size_metre__c = '3';
        p.Dash_Size_1__c = '4'; 
        p.Dash_Size_2__c = '1';
        p.Dash_Size_3__c = '2';
        p.Dash_Size_4__c = '3';         
        p.Stock_Image_1__c = 'Image 1';
        p.Stock_Image_2__c = 'Image 2';
        p.Stock_Image_3__c = 'Image 3';    
        insert p;
    
    List<Id> stockList = new List<Id>();
    stockList.add(p.Id);    
    Rest_websiteOutboundHandler.sendProductDetailsToPublicSite(stockList);
        //Test.setMock(HttpCalloutMock.class, new MockCallOutATTCallouts());
    }
    
    public static testMethod void unitTest2(){
    	
        Product_Category_Information__c pci = new Product_Category_Information__c();
        pci.Name = 'Fittings - HYD';
        pci.Category_Id__c = '11';
        pci.Stock_Description__c = 'Swage Hose Tails';
        
        insert pci;
        
        Product_Category_Information__c pci1 = new Product_Category_Information__c();
        pci1.Name = 'HOSE TAILS - HYD';
        pci1.Category_Id__c = '12';
        pci1.Stock_Description__c = 'S-Series 2-Piece Swage Fittings';
        
        insert pci1;
        
        Product_Category_Information__c pci2 = new Product_Category_Information__c();
        pci2.Name = 'WHP';
        pci2.Category_Id__c = '13';
        pci2.Stock_Description__c = 'WHP - CODE 62 (SAE) FLANGE CLAMP';
        
        insert pci2;
        
        Product_Category_Information__c pci3 = new Product_Category_Information__c();
        pci3.Name = 'Sales - Hydraulic Fittings';
        pci3.Category_Id__c = '14';
        pci3.Stock_Description__c = 'Sales - Hydraulic Fittings';
        
        insert pci3;
        
        product2 p = new Product2();
        p.Name = 'Test Product';
        p.QuantityUnitOfMeasure__c = 'Each';
        p.is_Hydraulic_Product__c = true;
        p.Bill_of_Material__c = false;
        p.IsActive = true;
        p.Show_on_Website__c = true;
        p.WordPress_Id__c = '12345';
        p.Primary_Group__c = '1110-10';
        p.Secondary_Group__c = '17';
        p.Secondary_Group_Display_Name__c = 'Swage Hose Tails';
        p.Tertiary_Group__c = '130';
        p.Tertiary_Group_Display_Name__c = 'Hydraulic Hose';
        p.Product_Family__c = 'WHP';
        p.Product_Family_Display_Name__c = 'S-Series 2-Piece Swage Fittings';
        p.b_in__c = '111';
        p.d_in__c = '222';
        p.e_in__c = '333';
        p.h_in__c = '444';
        p.l_in__c = '555';
        p.m_in__c = '666';
                 
        p.Stock_Image_1__c = 'Image 1';
        p.Stock_Image_2__c = 'Image 2';
        p.Stock_Image_3__c = 'Image 3';    
        insert p;
    
    List<Id> stockList = new List<Id>();
    stockList.add(p.Id);    
    Rest_websiteOutboundHandler.sendProductDetailsToPublicSite(stockList);
    }
    
    public static testMethod void unitTest3(){
    	
        Product_Category_Information__c pci = new Product_Category_Information__c();
        pci.Name = 'Quick Release Couplers';
        pci.Category_Id__c = '11';
        pci.Stock_Description__c = 'Quick Release Couplers';
        
        insert pci;
        
        Product_Category_Information__c pci1 = new Product_Category_Information__c();
        pci1.Name = 'QRC';
        pci1.Category_Id__c = '12';
        pci1.Stock_Description__c = 'QRC';
        
        insert pci1;
        
        Product_Category_Information__c pci2 = new Product_Category_Information__c();
        pci2.Name = 'PAV1 - QRC POPPET (ISO A)';
        pci2.Category_Id__c = '13';
        pci2.Stock_Description__c = 'PAV1 - QRC POPPET (ISO A)';
        
        insert pci2;
        
        Product_Category_Information__c pci3 = new Product_Category_Information__c();
        pci3.Name = 'Sales - Hydraulic Fittings';
        pci3.Category_Id__c = '14';
        pci3.Stock_Description__c = 'Sales - Hydraulic Fittings';
        
        insert pci3;
        
        product2 p = new Product2();
        p.Name = 'Test Product';
        p.QuantityUnitOfMeasure__c = 'Each';
        p.is_Hydraulic_Product__c = true;
        p.Bill_of_Material__c = false;
        p.IsActive = true;
        p.Show_on_Website__c = true;
        p.WordPress_Id__c = '12345';
        p.Primary_Group__c = '1110-10';
        p.Secondary_Group__c = '20';
        p.Secondary_Group_Display_Name__c = 'Quick Release Couplers';
        p.Tertiary_Group__c = '280';
        p.Tertiary_Group_Display_Name__c = 'QRC';
        p.Product_Family__c = 'PAV1';
        p.Product_Family_Display_Name__c = 'PAV1 - QRC POPPET (ISO A)';
        p.Nominal_Size_mm__c = 1;
        p.Rated_Flow_L_min__c = 2;
        p.Max_Work_Pressure_PSI__c = 3;
        p.Max_Flow_L_Min__c = 4;
        p.Min_Burst_Pressure_Male_PSI__c = 1;
        p.Min_Burst_Pressure_Female_PSI__c = 2;
        p.Min_Burst_Pressure_Coupled_PSI__c = 3;
        p.Fluid_Spillage_cc__c = 1;
           
        p.Stock_Image_1__c = 'Image 1';
        p.Stock_Image_2__c = 'Image 2';
        p.Stock_Image_3__c = 'Image 3';    
        insert p;
    
    List<Id> stockList = new List<Id>();
    stockList.add(p.Id);    
    Rest_websiteOutboundHandler.sendProductDetailsToPublicSite(stockList);
    }
}