BoaUAT/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Bill_of_Material__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill of Material</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_Hydraulic_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field identifies stock Item as a hydraulic product. This products are to be synced with web site and web portal.</description>
        <inlineHelpText>If true,this product is to be synced with web site and web portal.</inlineHelpText>
        <label>is Hydraulic Product</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/classes/batchProductUploadToWebPortal.cls
/*
* Description - batch class to push all products in a single go to web portal.
* Author - Centelon Team 
*/

public class batchProductUploadToWebPortal implements database.Batchable<sObject>,Database.AllowsCallouts{
    public Database.QueryLocator start(Database.BatchableContext bc) {
        
        
        string rec = 'SELECT Id from product2 where Bill_of_Material__c = false and is_Hydraulic_Product__c = true'; 
             
        return Database.getQueryLocator(rec);
    }
    
    public void execute(Database.BatchableContext bc, List<product2> scope){
        
       list<id> productIds = new list<id>();
        
        
        for(product2 p : scope){
            productIds.add(p.id);
        }

			Rest_WebPortalOutbondController.sendProductDetailsTrigger(productIds);
            
        
         
       
    }    
    public void finish(Database.BatchableContext bc){
            
          
    }    

    

}