BoaUAT/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Bill_of_Material__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill of Material</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stock_Image_1__c</fullName>
        <inlineHelpText>Stores link of product image from S3 bucket.</inlineHelpText>
        <label>Stock Image 1</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Stock_Image_2__c</fullName>
        <description>stores image url from s3 bucket.</description>
        <label>Stock Image 2</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Stock_Image_3__c</fullName>
        <description>stores image url from s3 bucket.</description>
        <label>Stock Image 3</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>WordPress_Id__c</fullName>
        <label>WordPress Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_Hydraulic_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field identifies stock Item as a hydraulic product. This products are to be synced with web site and web portal.</description>
        <inlineHelpText>If true,this product is to be synced with web site and web portal.</inlineHelpText>
        <label>is Hydraulic Product</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BoaUAT/src/classes/batchProductUploadToWebSite.cls
/*
* Description - batch class to push all products in a single go to web site.
* Author - Centelon Team 
*/

public class batchProductUploadToWebSite implements database.Batchable<sObject>,Database.AllowsCallouts{

    public Database.QueryLocator start(Database.BatchableContext bc) {
        
        
        string rec = 'SELECT Id from product2 where Bill_of_Material__c = false and is_Hydraulic_Product__c = true';
        //string rec = 'SELECT Id from product2 where wordpress_Id__c = \'\' AND Bill_of_Material__c = false and is_Hydraulic_Product__c = true';
        //string rec = 'SELECT Id,Name FROM Product2 WHERE WordPress_id__c = \'\' AND Bill_of_Material__c = false and is_Hydraulic_Product__c = true';
        //string rec = 'SELECT Id,Name,Stock_Image_1__c,Stock_Image_2__c,Stock_Image_3__c FROM Product2 WHERE WordPress_id__c = \'\' AND  AND Bill_of_Material__c = false and is_Hydraulic_Product__c = true
        system.debug('rec ' + rec);     
        return Database.getQueryLocator(rec);
    }
    
    public void execute(Database.BatchableContext bc, List<product2> scope){
        
       list<id> productIds = new list<id>();
        
        
        for(product2 p : scope){
            productIds.add(p.id);
        }

			Rest_websiteOutboundController.sendProductDetailstoWebSiteTrigger(productIds);
            
        
         
       
    }    
    public void finish(Database.BatchableContext bc){
            
          
    }    

    
}